AdguardTeam/companiesdb

- dist/adguard.json
> AGDNS-976 added-netflix-url

- dist/vpn_services.json
> VPN-847 add yandex domains

- dist/adguard.json
- dist/adguard_companies.json
https://github.com/AdguardTeam/companiesdb/issues/35
> Fix #35 nflximg.com

- dist/adguard.json
- dist/adguard_companies.json
https://github.com/AdguardTeam/companiesdb/issues/34
> Fix #34 showrss.info

- dist/adguard_companies.json
- dist/companies.json
Also correct registered trademark: https://trademarks.justia.com/owners/reddit-inc-2512865/
> Fix #44 Reddit icon

- dist/adguard.json
https://github.com/AdguardTeam/companiesdb/issues/23
> l-msedge.net

- dist/adguard.json
https://github.com/AdguardTeam/companiesdb/issues/24
> trafficmanager.net

- dist/adguard.json
- dist/adguard_companies.json
https://github.com/AdguardTeam/companiesdb/issues/25
> xtracloud.net

- dist/adguard.json
- dist/adguard_companies.json
https://github.com/AdguardTeam/companiesdb/issues/30
https://github.com/AdguardTeam/companiesdb/issues/31
> element.io

- dist/adguard.json
https://github.com/AdguardTeam/companiesdb/issues/29
> plex.direct

- dist/adguard_companies.json
https://github.com/AdguardTeam/companiesdb/issues/43
> Fix #43 snapchat.com

- dist/adguard.json
- dist/adguard_companies.json
https://github.com/AdguardTeam/companiesdb/issues/32
> matrix.org

- dist/adguard.json
https://github.com/AdguardTeam/companiesdb/issues/39
> icloud-content.com

- dist/adguard.json
- dist/adguard_companies.json
https://github.com/AdguardTeam/companiesdb/issues/40
> allawnos.com

- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/50
> safebrowsing.apple

- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/65
> cloudflare-dns.com

- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/66
> mail.me.com

- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/67
> phicdn.net

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/80
> media-lab.ai

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/81
> sectigo.com

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/82
> hbbtv.oztam.com.au

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/88
> telstra.com

- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/94
> Fix #94 akaquill.net

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/97
> Fix #97 whatsapp.net

- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/126
> Fix #126 gmail.com

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/96
> Fix #96 ntp.org

- source/trackers.json
```
! Windows Update
windowsupdate.com
! The Windows Push Notification Services
client.wns.windows.com
! Azure Blob Storage
blob.core.windows.net
! Windows Maps
maps.windows.com
! Windows Time Service
time.windows.com
```
> Added few Microsoft domains

- source/trackers.json
also removed invalid domain `adguardvpn.com`
> Splitted AdGuard domains to few trackers

- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/105
> Fix #105 github.dev

- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/135
> Fix #135 ms.applvn.com

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/117
https://github.com/AdguardTeam/companiesdb/issues/115
https://github.com/AdguardTeam/companiesdb/issues/116
https://github.com/AdguardTeam/companiesdb/issues/110
> Fix #117 lgsmartad.com

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/136
> Fix #136 nab.com.au

- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/128
> Fix #128 googlehosted.com

- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/127
> Fix #127 recaptcha.net

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/120
> Fix #120 sigmacdn.net

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/118
> Fix #118 freeviewaustralia.tv

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/113
> Fix #113 switch.tv

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/109
> Fix #109 sonos.com

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/122
> Fix #122 karambasecurity.com

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/106
> Fix #106 domain.glass

- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/114
> Fix #114 alphonso.tv

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/121
> Fix #121 netify.ai

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/92
> 3gppnetwork.org

- source/companies.json
- source/trackers.json
https://github.com/AdguardTeam/companiesdb/issues/123
> abc.net.au

- .github/ISSUE_TEMPLATE/database_correction.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
https://github.com/AdguardTeam/companiesdb/issues/154
> add issue template

- README.md
https://github.com/AdguardTeam/companiesdb/issues/173
| **Categories**                                                                                          | **Restrictions**                                         |
|---------------------------------------------------------------------------------------------------------|----------------------------------------------------------|
| misc, audio_video_player, customer_interaction, social_media                                            | availability of a law firm, sufficient popularity of use |
| pornvertising, advertising, essential, site_analytics, cdn, hosting, email, telemetry, mobile_analytics | will be added without restrictions                       |
| stand-alone sites not related to any service …
> add policy to readme

- index.ts
> Sort computed records alphabetically

- source/trackers.json
@jellizaveta Created a clean PR for this one.
> Add s-msedge.net

- source/companies.json
- source/trackers.json
Games company for Clash of Clans, Hay Day, Boom Beach, Clash Royale and Brawl Stars.
> add company and trackers for supercell

- source/companies.json
- source/trackers.json
CompanyID's have been kept the same to overwrite whotracks.me data resolving yarn warnings.
> Add companyID's to whotracks.me null data

- source/companies.json
- source/trackers.json
- Add parent company to Reddit, [Advance Publications, Inc.](https://publer.io/blog/who-owns-reddit/#:~:text=After%20one%20year%20of%20Reddit%27s,the%20magazine%20publisher%20Condé%20Nast.)
- Remove Reddit from source/companies
- Add Advance Publications, Inc. to source/companies
> Fix Advance Publications, Inc.

- source/companies.json
- source/trackers.json
- Fix Oracle company name, Oracle Corporation
- Add advertising product for Oracle Corporation, Oracle Infinity Behavioral Intelligence
- Add Oracle Infinity Behavioral Intelligence tracker
- Fix overwritten data from first commit
> Fix oracle

- dist/trackers.csv
- source/trackers.json
- Add Visual Studio IDE (Microsoft
- Add vsassets.io to Visual Studio's trackers
- Add new Microsoft Edge tracker
- Amend incorrectly discarded changes in first commit
> Fix Microsoft

- source/trackers.json
- Add reastatic.net to REA Group
> Fix reastatic.net

- source/companies.json
Note: companyincID kept the same to overwrite existing data
> Fix company name

- source/companies.json
- source/trackers.json
- Replace company Ubuntu with Canonical as the parent organisation
- Add Canonical to source/trackers
- Add Launchpad to source/trackers
- Add Snapcraft to source/trackers
- Amend domain owners
> Fix Canonical

- source/companies.json
Adobe Inc. is the correct company name as per their privacy policy.
> Change Adobe parent organisation

- source/companies.json
- source/trackers.json
Visiting any of these pages will show you a message from Cloudflare.
> Add cloudflarestream.com

- source/companies.json
- source/trackers.json
- Correct Disney company description
- Add VOD provider Disney Streaming, which was originally BAMtech, until purchased by Disney
- Add streaming service Disney+
> Fix #266 Add more Disney data

- source/companies.json
> Use Meta trade name

- source/companies.json
- source/trackers.json
- Yahoo! is now owned by Apollo Global Management (90%).
- Yahoo! now has 3 sections, the overarching company Yahoo!, Yahoo! Advertising, and Yahoo! Search.
- All obsolete data has been removed.
- Australian Government was correctly ordered.
> Fix Yahoo! data

- source/companies.json
- source/trackers.json
Network Time Protocol is a product, and not the company.
This pr fixes the company owner, being Network Time Foundation.
> Fix ntp company owner

- source/companies.json
- source/trackers.json
Alibaba is owned by SoftBank Group Corp, see top 5 shareholders [here](https://www.investopedia.com/articles/investing/111114/top-five-alibaba-shareholders.asp).
> Fix alibaba trading name

- source/trackers.json
Domain belongs to Microsoft SharePoint, a business collaboration tool.
> add sharepoint

- dist/vpn_services.json
- source/vpn_services.json
> Added OpenAI service

- dist/vpn_services.json
Added `mycdn.me` otherwise VK videos won't play.
> Updating VK

- source/trackers.json
> add app-analytics-services.com

- index.ts
before:
https://uploads.adguard.org/slByZL0OoPp6jRrQMc.png
after:
https://uploads.adguard.org/slH8Mr8K3Xli1lLUF2.png
> use tab character instead of spaces to decrease dist size

- source/trackers.json
- source/whotracksme.json
https://github.com/AdguardTeam/companiesdb/issues/398
> Fix #398 A typo in URLs

- source/vpn_services.json
https://github.com/AdguardTeam/companiesdb/issues/392
> Add Adobe Creative Cloud to VPN exclusions list

- source/vpn_services.json
https://github.com/AdguardTeam/companiesdb/issues/401
> Fix #401 githubcopilot.com

- source/vpn_services.json
https://github.com/AdguardTeam/companiesdb/issues/429
> Add Tiktok domains
