AdguardTeam/companiesdb

dist/vpn_services.json

Remove duplicate domain `byteoversea.com` from Tiktok service.

Remove duplicate domain from Tiktok service

---

dist/vpn_services.json

according to 
https://github.com/AdguardTeam/companiesdb/pull/77
https://github.com/AdguardTeam/companiesdb/issues/68
`gvt1.com` is used by Google

Fix gvt1.com in vpn services

---

source/trackers.json

Fixed `lflipboard.com` => `flipboard.com` loaded from Whotracksme.

Fixed a typo (Whotracksme)

---

source/companies.json
source/trackers.json

FarLight Games is the publisher for Lilith Games, publishing many major titles on current mobile app stores.

Add company FarLight Pte Ltd.

---

source/companies.json
source/trackers.json

> Vungle transforms how people discover and experience apps that delivers the highest value users through engaging video ads.
- Add parent company [Blackstone, Inc.](https://www.blackstone.com/news/press/blackstone-closes-acquisition-of-vungle-a-leading-mobile-performance-marketing-platform/)
- Add tracker company Vungle
- As a note, Vungle and [Liftoff](https://liftoff.io) have merged, and are both owned by Blackstone, Inc. At this stage there is no unified name for the merger. The [internal name](https://www.forbes.com/sites/johnkoetsier/2021/08/24/liftoff-and-vungle-merge-2-top-ten-mobile-ad-networks-owned-by-private-equity-fund-blackstone-combine-forces/?sh=5d8475203373) is "Liftoff+Vungle".
- Add tracker domain for Vungle which covers all current known subdomains

Add Vungle

---

source/companies.json
source/trackers.json

- Remove Foxtel from companies due to being a subsidiary of News Corp
- Amend Binge, Flash, Fox Sports, Foxtel, and Kayo Sports parent company to News Corp
- Add tracker REA Group Ltd. as a subsidiary of News Corp
- Add tracker realestate.com.au Pty Limited. as a subsidiary of News Corp

Amend News Corp subsidiaries

---

source/trackers.json

- Update GitHub, Inc. trading name based on their [privacy policy](https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement#)
- Update GitHub, Inc. parent company, due to being [acquired](https://news.microsoft.com/announcement/microsoft-acquires-github/) by Microsoft

Fix GitHub, Inc.

---

source/trackers.json

Fixed subsidiaries linked to AppNexus as a result.
- Alenty [acquired](https://www.prnewswire.com/news-releases/appnexus-acquires-leading-advertising-viewability-company-alenty-261851341.html) by AppNexus
- MediaGlu [acquired](https://www.forbes.com/sites/alexkonrad/2014/12/18/appnexus-buys-mediaglu-spends-200-million/#:~:text=AppNexus%20Draws%20Closer%20To%20IPO,For%20A%20Combined%20%24200%20Million) by AppNexus
- Open Adstream [acquired](https://www.prnewswire.com/news-releases/appnexus-completes-open-adstream-acquisition-and-closes-110-million-funding-round-281092902.html) by AppNexus
- AppNexus [acquired](https://www.adexchanger.com/online-advertising/xandr-formerly-appnexus-is-now-formerly-att-after-its-acquisition-by-microsoft/) by Microsoft
- url's for each tracker fixed
- MediaGlu …

Fix AppNexus parent company

---

source/companies.json
source/trackers.json

- Fix MediaLab.Ai trading name based on their [privacy policy](https://www.medialab.la/privacy-policy)
- Add MediaLab.Ai subsidiary, [Imgur](https://www.medialab.la), and Whisper
- Fix Kik's parent company, [MediaLab.ai](https://www.medialab.la)
- Add specific domains for Kik and Whisper

Fix MediaLab.Ai company

---

source/companies.json
source/trackers.json

- Add GameAnalytics to source/trackers
- Add GameAnalytics [parent](https://venturebeat.com/business/chinas-ad-tech-firm-mobvista-buys-denmarks-gameanalytics/) company Mobvista to source/companies
- Add tracker for GameAnalytics

Fix Mobvista

---

source/companies.json
source/trackers.json

- Alphabetised ByteDance
- Added BBK Electronics
- Added BBK Electronics as OPPO's [parent](https://en.wikipedia.org/wiki/BBK_Electronics)
It mentions in the Wikipedia that BBK Electronics is no longer registered, but this is not the case if you check the Chinese business registry.

Fix BBK Electronics

---

source/trackers.json

tizenservice.com belongs to TizenOS, which is the OS used on Samsung TV's.

Fix #267 Add tizenservice.com

---

source/companies.json
source/trackers.json

Let’s Encrypt is a free, automated, and open certificate authority (CA), run for the public’s benefit. It is a service provided by the [Internet Security Research Group (ISRG)](https://www.abetterinternet.org/).

Add parent organisation for Let's Encrypt

---

source/companies.json
source/trackers.json

- Nine Entertainment is one of Australia's largest TV networks
- Nine Digital Direct is their marketing platform

Add Nine Entertainment

---

source/companies.json
source/trackers.json

AdColony was purchased by Zynga, then by Digital Turbine. The domain added is still active and being used.

Add digital turbine

---

source/companies.json
source/trackers.json

Chartboost was purchased by take-two, is still active and used.

Add take two interactive software, inc 

---

source/trackers.json

add octocaptcha.com

---

source/trackers.json

Domain belongs to Outlook on the web.

add svc.ms

---

source/trackers.json

Domain belongs to Microsoft Edge app.

add spo-msedge.net

---

source/trackers.json

Domain belongs to Outlook on the web.

add cloud.microsoft

---

source/trackers.json

ads.assemblyexchange.com belongs to [MediaLab's](https://www.medialab.la) ad product, Assembly Exchange.

Add ads.assemblyexchange.com

---

source/trackers.json

"Amap is a leading provider of digital map content, navigation, and location-based solutions in China. Established in 2002, Amap is now a wholly owned subsidiary of Alibaba Group and is integrated with the e-commerce ecosystem of Alibaba Group. In 2018, Amap became the first Chinese maps service to navigate a path to 100 million daily users."

add amap.com

---

source/trackers.json

Service: AdGuard DNS
Sub-domain: [st.agrd.eu](url)
All records point to [1055008621.rsc.cdn77.org](url).
When visited, it shows it's connected to AdGuard.
> Code: NoSuchKey
> BucketName: adguard-websites-static
> RequestId: tx00000492549393940a719-00666a06a7-6271dc0-prg
> HostId: 6271dc0-prg-eu-1

Add agrd.eu

---

README.md
dist/vpn_services.json
index.ts
source/vpn_services.json

https://github.com/AdguardTeam/companiesdb/issues/371
AG-29349

#371 update modified time

---

source/trackers.json

Domain used for iCloud+ Private Relay queries, and Firefox secure DNS queries.
Refs
https://www.fastly.com/blog/icloud-private-relay-and-a-privacy-preserving-internet/
https://www.fastly.com/blog/firefox-fastly-take-another-step-toward-security-upgrade/

add fastly-masque.net

---

source/vpn_services.json

Not sure about `mycdn.me`, but it was needed earlier https://github.com/AdguardTeam/companiesdb/pull/361.
This is necessary so that VK videos can be opened.

Updating VK domains

---

source/trackers.json

Domain identified when visiting outlook.office.com within the AdGuard DNS query logs.

add dual-s-msedge.net to list of trackers

---

source/trackers.json

Request: vod-hevc-drm5-cf.foxtelgroupcdn.net.au
Service: AdGuard DNS
Product: Binge TV

add foxtelgroupcdn.net.au
